name: "Build"

on: 
  pull_request:
    
  push:
    branches:
      - "main"
  
  workflow_dispatch:

env: 
  SONAR_CLOUD_PROJECT_KEY: gethemebrika_ApiApplication
  SONAR_CLOUD_ORG: gethemebrika-1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  TEST_FOLDER_PATH: /Tests

jobs:
  Build:
   runs-on: ubuntu-latest
   permissions:
      id-token: write
      contents: read
      checks: write
   name: CI Build
   steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available.  
    
     - name: Cache SonarCloud packages
       uses: actions/cache@v3
       with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

     - name: Install SonarCloud scanners
       run: |
          dotnet tool install --global dotnet-sonarscanner
          
     - name: Start SonarCloud
       run: |
           dotnet-sonarscanner begin /k:"${{env.SONAR_CLOUD_PROJECT_KEY}}" /o:"${{env.SONAR_CLOUD_ORG}}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml  /d:sonar.host.url="https://sonarcloud.io"
    
     - name: Restore packages
       run: |
          dotnet restore

     - name: Build Solution
       run: |
         dotnet build --configuration Release --no-restore
    
     - name: Run Tests
       run: |
          chmod a+x run_tests.sh
            ./run_tests.sh ${{env.TEST_FOLDER_PATH}} 

     - name: End SonarCloud
       run: |
         dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    
     - name: Parse Test results
       uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226 # v1.6
       if: success() || failure()
       with:
        name: Test results
        path: TestResults/*.trx
        reporter: dotnet-trx
        list-suites: 'failed'
        fail-on-error: 'true'